services:
  mongodb:
    image: mongo:6
    container_name: senseflow_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: senseflow_live
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
